version: '3'
services:
  db:
    restart: always
    tty: true
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_DB: shop
      POSTGRES_PASSWORD: root
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: ["postgres",
              ### Configure Logging
              "-c", "log_statement=all",
              "-c", "log_destination=stderr",
              "-c", "log_connections=on",
              "-c", "log_disconnections=on"]
volumes:
  pg-data:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/postgresql/data
      o: bind
